# Generated by Django 5.0.1 on 2024-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_going_command',
            field=models.IntegerField(default=0),
        ),
    ]
